#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0
### Has an outline
#remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/merlot@v0.2.0
title: "VisionMD"
description: An user-friendly, open-source software platform designed to automate video-based kinematic analysis of motor tasks for assessment of motor dysfunction in movement disorders
